config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  get 'welcome/index'
  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  get 'auth/logout' => 'auth0#logout'
  get 'dashboard' => 'dashboard#show'

  
  resources :articles do
    resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_and_belongs_to_many :tags
    validates :title, presence: true,
                      length: {minmum: 5, maximum: 255}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include Secured
    def new
        @article = Article.new
    end

    def create
        user_id = session[:userinfo]["uid"]
        @article = Article.new(article_params)
        @article.owner_id = user_id
        tagging_service = TaggingService.new(@article)
        tagging_service.associate_tags
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
        @html_content = markdown.render(@article.text)
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            tagging_service = TaggingService.new(@article)
            tagging_service.associate_tags
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    def index
        @articles = Article.all.order(updated_at: :desc)
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
    include LogoutHelper
    def callback
        # This stores all the user information that came from Auth0
        # and the IdP
        session[:userinfo] = request.env['omniauth.auth']
    
        # Redirect to the URL you want after successful auth
        redirect_to '/dashboard'
      end
    
      def failure
        # show a failure page or redirect to an error page
        @error_msg = request.params['message']
      end

      def logout
        reset_session
        redirect_to logout_url
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)

    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end

end

app/controllers/concerns/secured.rb
module Secured
    extend ActiveSupport::Concern
    included do
        before_action :logged_in_using_omniauth?
    end

    def logged_in_using_omniauth?
        unless session[:userinfo].present?
            flash[:error] = "You must be logged in to use this"
            redirect_to '/'
        end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Secured
  def show
    Rails.logger.info(session[:userinfo].inspect)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render layout: 'marketing_page' 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def my_link_to(text, href)

        if href == request.url
            current_class = 'nav-link active'
        else
            current_class = 'nav-link'
        end
        "<a href='#{href}' class=#{current_class}>#{text}</a>".html_safe
    end
end 

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
    def logout_url
        auth0_domain = Rails.application.credentials.auth0[:domain]
        client_id = Rails.application.credentials.auth0[:client_id]
        request_params = {
            returnTo: root_url,
            client_id: client_id
        }

        URI::HTTPS.build(host: auth0_domain, path: '/v2/logout', query: to_query(request_params)).to_s
    end

    private
        def to_query(hash)
            hash.map { |k, v| "#{k}=#{URI.escape(v)}" unless v.nil?}.reject(&:nil?).join('&')
        end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
     <% if @article.errors.any? %>
        <div id="error_explanation">
        <em>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
        </em>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <%end%>


    <%= form_with(model: @article, local: true) do |form| %>
    
        <div class='form-element'>
            <label>
                <%= form.label :title %>
                <%= form.text_field :title %>
            </label>
        </div>
        <div class='form-element'>
          <%= form.text_area :text %>
        </div>
        <div class='form-element'>
            <%= form.submit %>
        </div>
    <% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<div class='container'>
    <h1> Edit: "<%= @article.title %>"</h1>
    <%= link_to 'Back', articles_path %>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class='container'>
<h1>All Articles</h1>

<table>
  <tr>
    <th>Owner</th>
    <th>Title</th>
    <th>Updated</th>
    <th></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td class='table-nowrap'> <%= article.owner_id %></td>
      <td>
      <%= link_to article.title, article_path(article) %>
      </td>
      <td><%= article.updated_at %></td>
      <td>
        <%= link_to 'Edit', edit_article_path(article) %>
        &nbsp;
        <%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/articles/new.html.erb
<div class="container">
    <h1>New Article</h1>
    <%= link_to 'Back', articles_path %>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
    <h1>
    <%= @article.title %>
    </h1>
    <%= link_to 'Edit', edit_article_path(@article) %> | &nbsp;
    <%= link_to 'Back', articles_path %>
    <p class="content">
    <%=raw @html_content %>
    </p>

    <%= render @article.comments %>
        
    <h2>Add a comment:</h2>
    <%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
  <p>
    <strong><%= comment.commenter %> says:</strong> <%= comment.body %>

    <em>
     <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
    </em>
  </p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/dashboard/show.html.erb
<div class='container'>
    <h1>Dashboard</h1>
    <img class='profile-pic' src="<%=session[:userinfo]["info"]["image"]%>">
    <p>Welcome <%=session[:userinfo]["info"]["name"]%> <p>
    <%= button_to 'Log Out', auth_logout_path, method: :get %>

    <h2> Debug stuff </h2>
    <pre>
        <%= session[:userinfo].inspect %>
    </pre>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby notes - like any other note taking applicaiton but this one has batteries included!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# TODO: we could use params[:controller] here to load js on every page! %>
    <%= javascript_pack_tag 'articles', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  </head>

  <body>

    <header>
      <nav>
        <%= my_link_to 'Write', new_article_url %> | &nbsp;
        <%= my_link_to 'Find', articles_url %>  | &nbsp;
        <%= my_link_to 'Profile', dashboard_show_url  %>
      </nav>
    </header>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/layouts/marketing_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby notes - like any other note taking applicaiton but this one has batteries included!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# TODO: we could use params[:controller] here to load js on every page! %>
    <%= javascript_pack_tag 'articles', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script src="https://kit.fontawesome.com/1ac566fe5f.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu|Ubuntu+Mono&display=swap" rel="stylesheet"> 
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="home-page">
    <div class="left-pane">
        <div class="title">
                <span>robot</span>
                <span>NOTES</span>
        </div>
    </div>

    <div class="right-pane">
        <div class='content'>
        <% if not session[:userinfo] %>
            <p>
            Join an awesome community of writers
            </p>
            <%= button_to 'Login or Register', 'auth/auth0', method: :post %>
        <% else %>
        <p>Welcome back <%= session[:userinfo]["info"]["nickname"] %>.</p>
        <%= link_to 'Write an Article', controller: 'articles' %> | &nbsp;
            <%= link_to 'Find an Article', controller: 'articles' %> | &nbsp;
            <%= link_to 'View Dashboard', 'dashboard#show' %>
        <% end %>
        </div>
    </div>
</div>